language: node_js
node_js:
- 6
addons:
  firefox: 49.0.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
script: npm run dist
notifications:
  slack:
    secure: UIMsZ74LfdIB5HY2fQ0aRRfhBU6iLX/J+b33bAELpE3jNUOuzllsgjczlfGEySFg4M48XOprbQPWDU9TX6L7QKx1z2Kf/VaWvTSKkxyf8PC9sr7WZ8ty2VeqXsgzofqItq8y1+/LL19aON8pdR/mgU4fEjN4wfDk0CJlWcaySHWFkVTJh2mzz3sWQzGgWPtZhbdylVb4zasWMQybY1Dr2OAS3eT3Hj4eIrmVf6tXm3hUENQv2uU8fqLXJcXFNBCHy35Xy8NPDmtutZOl0TkKzDmiFCmMsusMIqlCWB17c0rLkcUCM2KkQjBZcnUQqSnLnDXcdlbMmIz3+rm+pHkfIPQRgHeraT19wbNThOq+neLYN5ifzBFqbTFrWRXlRDbywu2txoGqeJ0p95BAlQEz0m7Wka6f767R9g63nyRE76GKC6+CGafUAGNHYsiP81xDScWLxa4FsIXlIme4+VP9usSyRoQnyXMQJ30mE6gReFBvFXu1evP5Ef702MIIfgcoFLHFdzu1uuvMyT8xxQMkZZtjoBYnLLhgkXkDA+c2qzcS/PsWdaRgeUIu7ZmKWbcZvENMuUzitLCLVgYmDIBiI1mgmQi7nBQEw6zau8UT5a8E2GEw5uqhlp3P8w9UXXv2yXPmmtonTNb4dlKodTAQ2wOVqqtTioUDmI9K9tpeJoo=
    on_success: change
    on_failure: always
deploy:
  - provider: releases
    api_key:
      secure: IeIhf4uIp8AUEd7ImsoZo1/ynXxylGe7OAJKqZonnBmVUhe/1D52WOBOsHqnxe4hLH1ZZKTUMgLAAY09HzmjczpLBI8PKPOEJllbwBr/A+EJqontVwP9iEFelcDOARHzfFRKrj23FRzRcZ7U6HK2YxG2h8I9OYN6kCL3vptKDub3YHXBbJrDYjwAJfPoR3ko62i02fWV6s5JKpXq4XfSUZA0Ajy2jIfA/NfbvO0146bh8XkZoQJGub3nNL7oHRG69kBYwVaV7bgsZCBCMkkHRCX/zaqfipPCh6aWt7ksKaq2YtEj5EHYHVfLkPSAoKeC0H6Ct6EPSlbp0YzoinMFaNHb5qGjFahSUroeolqnkJ/L1oDhUAP2Orp7rJoeeahHZQKq1pCsCp2rVlxEbQYxsdB34vuzdLvfvpPkhbERJc7ZPpwDWl3x1lE/ufLlQiHyp1OzQ81OmoGOinbGZBGmpekg7GQA5bKjnlSwMSSIRqqpdw4Zb6NtCyLh7BrrGBI5LqXxfKFNEQQWMXPgId19YBrlNef5jSjgo5+etscxa9Sj+r893dO9V82FdF35Jj2rLoCHkOyAatlbvcz4qyfpkn+J1DmRVqPPdlEWK/gX36yVhV+CstLxnH8fJknfrw2ILA+p1CAGRm4SH3Jap9Bjagppup0rxWJXndvxsAMacZ8=
    file: dist/phovea_vis.tar.gz
    on:
      tags: true
      repo: phovea/phovea_vis
  - provider: npm
    email: samuel.gratzl@jku.at
    api_key:
      secure: X0QuouugY8RI+/P3kJQe9f/cRDKvN1qNM2jr2tAKgFLHKxhrpwA6dFbaD0GcXbVH9Gt0kk66VkiwFhfA1SlRp4YiqiGCcC8KTeps/NLeEpP7Jxbr4JW4a3ueT0RzFbem+JKMERP0dXXIfT4xL1WeLb37Fone7Bc9bRzv/vwKzCmqUMB/T/mzWd+4OIDoRudFif4gt3f3cMUX/L4i7X4Z8ELMre47XTse/aIICk1RMMBPWR2ZIytbWEfbNAVNeed/1o67m/E3t3Bc+pHf91PusXHvtsORW8K9tmldzN28ciQvlCkPdlQnA4ihhcb5OHhl+40+cFvRS4uZ8DQP10haypbzCpWqN7Jv/vw1FwZ8TnloSuESyJhzuj6LG7Me1oJ8W1bkYOlBmdTmJtgbWNUHoTO0UlMUPUMVRxP0Rj/HqOjqvixFIwcQ3quZEtTGTHgYhCwqm8UnUnoMjOKLj4YqRz9wjOl+Hfooq1HPUrAkJ2rkxRSNFipYJoxu0UD/V/qSc+drIXaeOzhqhA4Zz468j+w52Xqr2H4abCtMh6qSMfdhxqznm6ercpHTdW0StG4g7sH7Sg6e0bjl1ry9PDx9O48i9MU3C+1vO8+1Fc3SSal1o20yIFhaJ5BurhRw3kiMhRh+Mc6T5+YZC0fJF09FmDMRfR+LhnxjWtgEt3NDh3I=
    on:
      tags: true
      repo: phovea/phovea_vis
